apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    {{- with .Values.worker.labels }}
    {{ toYaml . }}
    {{- end }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      name: worker-pod

  template:
    metadata:
      labels:
        name: worker-pod
    spec:
      initContainers:
      - name: waiting-for-postgres
        image: postgres:latest
        command: ['sh', '-c', 
          'until pg_isready -h voting-app-postgresql -p 5432; 
          do echo waiting for database; sleep 2; done;']
      - name: waiting-for-redis
        image: redis:latest
        command: ['sh', '-c', 
          'until redis-cli -h voting-app-redis-master -p 6379; 
          do echo waiting for redis; sleep 2; done;']
      containers:
      - name: worker-app
        image: {{ .Values.worker.image }}
        imagePullPolicy: {{ .Values.worker.imagePullPolicy }}
        env:
        {{- with .Values.worker.env }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        resources:
        {{- with .Values.worker.resources }}
        {{ toYaml . | nindent 10 }}
        {{- end }}

