---
version: "1.0"

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass password
    ports: ["6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - frontend
      - backend

  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting-app-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - frontend
      - backend
    volumes:
      - "db-data:/var/lib/postgresql/data"

  result-webapp:
    build:
      context: ./voting-app/result-webapp
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - frontend
    ports:
      - "9091:80"

  vote-webapp:
    build:
      context: ./voting-app/vote-webapp
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - frontend
    ports:
      - "9090:80"

  worker:
    build:
      context: ./voting-app/worker
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data: {}
