---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: voting-app-stack
  labels:
    app: postgres
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: voting-app-stack
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M